name: dart_io
publish_to: none
repository: https://github.com/gordianknotC/dart_io.git
description: A starting point for Dart libraries or applications.
version: 0.0.1
# version: 1.0.0
# homepage: https://www.example.com
# author: gordianknot <email@example.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  quiver: ^3.2.1  #collection utilities
  path: ^1.8.3    #file system path
  yaml: ^3.1.1   #yaml
  archive: ^3.3.6    #compression utility
  tripledes: ^2.1.0    #encryption / decryption
  http_server: ^1.0.0    #simple http server
  rxdart: ^0.27.7     #stream controller 0.20.0...
  dart_common:
    git:
      url: https://github.com/gordianknotC/dart_common.git
      ref: HEAD

dev_dependencies:
  test: ^1.0.0
